/**
 * Intenciones para la paleta «Buscar e ir» del admin.
 * Cada ítem lleva a la pantalla donde ya existen los números y cálculos (no duplicamos lógica acá).
 */
export type AdminCommandIntent = {
  id: string;
  /** Título corto en el listado */
  title: string;
  /** Dónde verás totales / tablas / gráficos */
  hint: string;
  /** Palabras y frases que el usuario podría decir o escribir */
  keywords: string[];
  path: string;
  search?: string;
  hash?: string;
  /** Orden cuando no hay texto de búsqueda (menor = más arriba) */
  priority: number;
};

export const ADMIN_COMMAND_INTENTS: AdminCommandIntent[] = [
  {
    id: "dashboard",
    title: "Inicio — resumen del día",
    hint: "KPIs, mapa rápido, cartera e ingresos del mes (totales ya calculados en el servidor).",
    keywords: ["inicio", "home", "panel", "resumen", "hoy", "kpi", "indicadores", "dashboard"],
    path: "/admin/dashboard",
    priority: 1,
  },
  {
    id: "cartera",
    title: "Cartera por cobrar (detalle)",
    hint: "Lista de deudores y saldos por envío; baja hasta el bloque de cartera.",
    keywords: [
      "cartera",
      "cobrar",
      "deuda",
      "deudores",
      "saldo",
      "pendiente de pago",
      "quien debe",
      "morosos",
    ],
    path: "/admin/dashboard",
    hash: "cartera-por-cobrar-detalle",
    priority: 2,
  },
  {
    id: "pendientes",
    title: "Envíos pendientes de aprobar",
    hint: "Lista para cotizar, asignar o confirmar (filtrada como en Inicio).",
    keywords: ["pendientes", "aprobar", "solicitudes", "cotizar", "nuevos pedidos", "sin cotizar"],
    path: "/admin/envios",
    search: "vista=pendientes",
    priority: 3,
  },
  {
    id: "pendientes-atrasados-interno",
    title: "Pendientes sin avanzar (cotización o equipo)",
    hint: "Solo los que faltan cotización o asignación de equipo.",
    keywords: [
      "sin avanzar",
      "atascados",
      "falta cotizar",
      "falta equipo",
      "no avanzan",
      "trabajo atrasado",
    ],
    path: "/admin/envios",
    search: "vista=pendientes_sin_avanzar",
    priority: 4,
  },
  {
    id: "en-curso",
    title: "Viajes en curso",
    hint: "Pedidos en ruta: recogidos y en tránsito hacia la entrega (lo que suele llamarse «en tránsito»).",
    keywords: [
      "en curso",
      "en transito",
      "en tránsito",
      "pedidos en transito",
      "pedidos en tránsito",
      "ordenes en transito",
      "órdenes en tránsito",
      "ruta",
      "camino",
      "viajes activos",
      "chofer en ruta",
      "que van en camino",
      "cargas en ruta",
    ],
    path: "/admin/envios",
    search: "vista=en_curso",
    priority: 5,
  },
  {
    id: "confirmados",
    title: "Envíos confirmados (listos para salir)",
    hint: "Aprobados con equipo; aún sin recoger.",
    keywords: ["confirmados", "listos para salir", "con equipo", "asignados"],
    path: "/admin/envios",
    search: "vista=confirmados",
    priority: 6,
  },
  {
    id: "retrasos",
    title: "Solo retrasos (fecha vencida)",
    hint: "Entregas comprometidas vencidas sin cerrar.",
    keywords: ["retrasos", "atrasados", "tarde", "vencidos", "fecha pasada"],
    path: "/admin/envios",
    search: "vista=retrasos",
    priority: 7,
  },
  {
    id: "alertas",
    title: "Rechazos en destino + retrasos",
    hint: "Vista combinada de alertas operativas (misma lógica que el KPI del inicio).",
    keywords: ["alertas", "problemas", "rechazos y retrasos", "incidentes", "destino"],
    path: "/admin/envios",
    search: "vista=alertas",
    priority: 8,
  },
  {
    id: "entregas-hoy",
    title: "Entregas cerradas hoy",
    hint: "Lista de cierres del día.",
    keywords: ["entregas hoy", "cerrados hoy", "entregado hoy"],
    path: "/admin/envios",
    search: "vista=entregas_hoy",
    priority: 9,
  },
  {
    id: "entregas-revision",
    title: "Entregas de hoy a revisar",
    hint: "Programados para hoy sin cerrar o sin receptor.",
    keywords: ["revisar", "falta receptor", "entrega pendiente hoy", "completar entrega"],
    path: "/admin/envios",
    search: "vista=entregas_hoy_revision",
    priority: 10,
  },
  {
    id: "rechazados-admin",
    title: "Rechazos de oficina o en retiro",
    hint: "Lista filtrada en Envíos.",
    keywords: ["rechazados", "rechazo admin", "no cabe en camion", "pre ruta", "solicitud rechazada"],
    path: "/admin/envios",
    search: "vista=rechazados",
    priority: 11,
  },
  {
    id: "rechazos-destino",
    title: "Rechazo en destino",
    hint: "Incidencias en ruta o descarga; Envíos.",
    keywords: ["rechazo destino", "rechazo en entrega", "en entrega"],
    path: "/admin/envios",
    search: "vista=rechazos_entrega",
    priority: 12,
  },
  {
    id: "todos-envios",
    title: "Todos los envíos (sin filtro)",
    hint: "Auditoría: cualquier estado en una tabla.",
    keywords: ["todos", "listado completo", "auditoria", "auditoría", "exportar mental"],
    path: "/admin/envios",
    search: "vista=todos",
    priority: 25,
  },
  {
    id: "vista-tabla-envios",
    title: "Vista tabla de envíos (avanzada)",
    hint: "Misma data que en Inicio, en filas con filtros y búsqueda global.",
    keywords: [
      "tabla envios",
      "tabla envíos",
      "grilla",
      "lista completa",
      "pantalla envios",
      "pantalla envíos",
      "modulo envios",
      "módulo envíos",
    ],
    path: "/admin/envios",
    priority: 26,
  },
  {
    id: "pagos",
    title: "Pagos y comprobantes",
    hint: "Validar transferencias y estado de cobro.",
    keywords: ["pagos", "transferencias", "comprobantes", "validar pago", "abonos"],
    path: "/admin/pagos",
    priority: 13,
  },
  {
    id: "facturas",
    title: "Facturas",
    hint: "Documentos y totales facturados.",
    keywords: ["facturas", "dte", "boletas", "facturacion", "facturación"],
    path: "/admin/facturas",
    priority: 14,
  },
  {
    id: "rentabilidad",
    title: "Rentabilidad y márgenes",
    hint: "Gráficos y filtros con cálculos de rentabilidad por período.",
    keywords: [
      "rentabilidad",
      "margen",
      "ganancia",
      "utilidad",
      "numeros finanzas",
      "números finanzas",
      "cuanto ganamos",
      "resultado",
    ],
    path: "/admin/rentabilidad",
    priority: 15,
  },
  {
    id: "egresos",
    title: "Egresos y gastos",
    hint: "Resumen de salidas de dinero.",
    keywords: ["egresos", "gastos", "costos", "salidas"],
    path: "/admin/egresos",
    priority: 16,
  },
  {
    id: "precios",
    title: "Precios y tarifas base",
    hint: "Parámetros para cotizar (fees, mínimos, etc.).",
    keywords: ["precios", "tarifas", "cotizacion automatica", "cotización", "fee", "tarifa"],
    path: "/admin/precios",
    priority: 17,
  },
  {
    id: "liquidaciones",
    title: "Liquidaciones a choferes",
    hint: "Cálculos y cierres de comisiones / liquidaciones.",
    keywords: ["liquidaciones", "choferes pago", "comision chofer", "comisión", "pagar chofer"],
    path: "/admin/liquidaciones-choferes",
    priority: 18,
  },
  {
    id: "mapa",
    title: "Mapa en vivo",
    hint: "Seguimiento geográfico de envíos.",
    keywords: ["mapa", "ubicacion", "ubicación", "gps", "seguimiento"],
    path: "/admin/mapa",
    priority: 19,
  },
  {
    id: "clientes",
    title: "Clientes",
    hint: "Directorio y altas: también en Inicio (atajo Clientes) y Buscar.",
    keywords: ["clientes", "empresas", "cuentas"],
    path: "/admin/clientes",
    priority: 20,
  },
  {
    id: "flota",
    title: "Flota (vehículos)",
    hint: "Misma gestión que el panel de Inicio (icono junto a Choferes), en pantalla completa.",
    keywords: ["flota", "vehiculos", "vehículos", "camiones", "patentes"],
    path: "/admin/flota",
    priority: 21,
  },
  {
    id: "choferes",
    title: "Choferes",
    hint: "Conductores y asignaciones.",
    keywords: ["choferes", "conductores", "drivers"],
    path: "/admin/choferes",
    priority: 22,
  },
  {
    id: "marketplace",
    title: "Marketplace (beta)",
    hint: "Canal adicional tipo app de carga pesada (ofertas, comisión y métricas).",
    keywords: ["marketplace", "uber carga", "plataforma", "comision", "comisión"],
    path: "/admin/marketplace",
    priority: 22,
  },
  {
    id: "reportes",
    title: "Reportes",
    hint: "Informes exportables y vistas resumen.",
    keywords: ["reportes", "informes", "excel", "csv"],
    path: "/admin/reportes",
    priority: 23,
  },
  {
    id: "auditoria",
    title: "Auditoría",
    hint: "Trazabilidad y cambios registrados.",
    keywords: ["auditoria", "auditoría", "log", "historial cambios"],
    path: "/admin/auditoria",
    priority: 24,
  },
  {
    id: "ajustes",
    title: "Ajustes generales",
    hint: "Configuración de la empresa y preferencias.",
    keywords: ["ajustes", "configuracion", "configuración", "opciones", "empresa"],
    path: "/admin/ajustes",
    priority: 26,
  },
  {
    id: "soporte-choferes",
    title: "Soporte a choferes",
    hint: "Mensajes e incidencias del equipo en ruta.",
    keywords: ["soporte", "ayuda chofer", "mensajes chofer"],
    path: "/admin/soporte-choferes",
    priority: 27,
  },
];
